### ISSUE TITLE
Update to latest scalaz-stream and akka-streams

### ISSUE THREAD

**Issue by zenaptix** [krasserm/streamz#10]
I am not sure what the long term prospects for this project is.  I am using Akka and Camel quite extensively in production and I think this project could be very valuable.  I have forked the project to try and apply the update to the above libraries, but there are a number of API changes that makes it more than just a trivial change-over. I would be happy to assist, if I can get some guidance while familiarizing myself with the code.
Regards
Ian

**Comment by krasserm** [comment]
Hi Ian,

thanks for offering help! Upgrading to the latest versions of akka-streams and scalaz-stream is overdue. If you have any questions, please add them to this ticket. Looking forward to your pull request. /cc @volkerstampa 

Cheers,
Martin

**Comment by zenaptix** [comment]
Hi Martin
I have adapted most of the code  but I am having a problem to fix the test class AkkaStreamSpec. It implements a FoldSink class that extends a deprecated SinkWithKey (snip attached)
I am not sure how to adapt this to the new release. Maybe you can give me a few pointers what to use from the new Streams API. To be honest, I am not too clear on the purpose of this class, mostly due to my lack of a proper understanding of the library (hopefully I can fix that as we get more documentation in the next release).
Regards
Ian



final case class FoldSink[U, Out](zero: U)(f: (U, Out) ⇒ U) extends SinkWithKey[Out, Future[U]] {
  override def attach(flowPublisher: Publisher[Out], materializer: ActorBasedFlowMaterializer, flowName: String): Future[U] = {
    val promise = Promise[U]()

    Source(flowPublisher).transform(() ⇒ new Stage[Out, U] {
      var state: U = zero
      override def onPush(in: Out): immutable.Seq[U] = {
        state = f(state, in)
        Nil
      }

      override def onTermination(end: Option[Throwable]) = {
        end match {
          case None    ⇒ promise.success(state)
          case Some(e) ⇒ promise.failure(e)
        }
        Nil
      }

      override def onError(cause: Throwable) = ()
    }).consume()(materializer.withNamePrefix(flowName))

    promise.future
  }
  def future(m: MaterializedMap): Future[U] = m.getSinkFor(this)



Ian de Beer






zenAptix (Pty) Ltd
176 Dorp Street. Stellenbosch,
South Africa

Work: +27 21 887 3110
Mobile: +27 82 887 0926
web: http://www.zenaptix.com <http://www.zenaptix.com/>

**Comment by volkerstampa** [comment]
Hi Ian,

in the akka-streams release used previously the `FoldSink` had a bug so I copied its implementation and fixed the bug locally (and also provided a patch to akka). The bug-fix made it into later releases of akka-streams so the local copy is now obsolete and can be replaced by this [FoldSink](http://doc.akka.io/api/akka-stream-and-http-experimental/1.0-M2/#akka.stream.scaladsl.FoldSink).

HTH
Volker

**Comment by zenaptix** [comment]
Hi Volker
Thanks for the response.  It appears as though a FoldSink is not compatible with the Source.to() function - which requires a Sink[I]  not FoldSink[List[O],O]. It is the case regardless of whether I use Sink.fold or FoldSink. I am using AkkaStream version 1.0-M2.

val sink = FoldSink[List[O], O](List[O]())(_ :+ _)  // or val sink = Sink.fold(Nil)(_ :+ _)
val flow: RunnableFlow = source.to(sink)

Regards
Ian







zenAptix (Pty) Ltd
176 Dorp Street. Stellenbosch,
South Africa

Work: +27 21 887 3110
Mobile: +27 82 887 0926
web: http://www.zenaptix.com <http://www.zenaptix.com/>

**Comment by volkerstampa** [comment]
Hi Ian,

I am not sure what your problem is. The following code compiles for me:

```scala
  private def toList[O](source: Source[O])(implicit executionContext: ExecutionContext): Future[List[O]] = {
    val sink = Sink.fold[List[O], O](Nil)(_ :+ _)
    val materializedMap = source.to(sink).run()
    materializedMap.get(sink)
  }
```
What do you mean with "FoldSink is not compatible with the Source.to()". What error do you get?

Cheers
Volker

**Comment by zenaptix** [comment]
Thanks again. I found the issue - the original code that I am refactoring from has:

private def toList[I, O](flow: FlowWithSource[I, O])(implicit executionContext: ExecutionContext): Future[List[O]]

while your code now reads:

private def toList[O](source: Source[O])(implicit executionContext: ExecutionContext): Future[List[O]]

Regards
Ian

Ian de Beer






zenAptix (Pty) Ltd
176 Dorp Street. Stellenbosch,
South Africa

Work: +27 21 887 3110
Mobile: +27 82 887 0926
web: http://www.zenaptix.com <http://www.zenaptix.com/>

**Comment by krasserm** [comment]
Hi Ian, any update on this? Cheers, Martin

**Comment by zenaptix** [comment]
Hi Martin
I had a month-end deadline to meet and thing got a bit crazy. I shall attend to akka-streams again this week and will keep you posted on progress.
I am also using your Cassandra Plugins for Akka Persistence. The use case is for a Vehicle Tracking system where fleet-owners subscribe to a feed of their vehicles. I create a Persistent actor for each vehicle and a View for each subscription to a vehicle, so that when a subscription is received the client gets both the historic data and the currently streamed data. This is for production purposes. I have tested the concept and it works quite well. My biggest concern is the future of the project.
Are there any long term plans for the project (e.g. make part of Typesafe supported offering/Akka)? We are in talks with Typesafe about support.
Regards
Ian







zenAptix (Pty) Ltd
176 Dorp Street. Stellenbosch,
South Africa

Work: +27 21 887 3110
Mobile: +27 82 887 0926
web: http://www.zenaptix.com <http://www.zenaptix.com/>

**Comment by krasserm** [comment]
> I had a month-end deadline to meet and thing got a bit crazy. I shall attend to akka-streams again this week and will keep you posted on progress. 

Great, thanks for keeping working on this.

> Are there any long term plans for the project (e.g. make part of Typesafe supported offering/Akka)? We are in talks with Typesafe about support.

Personally, I want to further update the plugins if there are new Cassandra and/or Akka versions, adding new features, if needed. Should you need professional support, for example for a high prio feature, you can also contact me directly.

Regarding Typesafe, I don't know if they plan to officially support the plugin. If yes, it will probably move into the akka project, which would mean EOL for krasserm/akka-persistence-cassadra. The same thing already happened to krasserm/akka-persistence-testkit. I'd be happy to support that initiative.

**Comment by zenaptix** [comment]
Hi Martin
For some reason I thought you were formally associated with Typesafe. I would like to consider your offer for professional support and will discuss it with my client. Do you have a rate chart or consulting fee I can use?
Just a bit of background, my company is developing a Big Data ingestion system for the largest vehicle tracking company in South Africa: Altech Netstar.
We use Scala 2.11.5, Akka 2.3.9. akka-persistence-cassandra 4.0-SNAPSHOT amongst others.  (I want to use streamz for the enrichment and dissemination of messages - especially via Camel.)

I have a question regarding the use of Akka Persistence using Cassandra. We are getting system failures and I am trying to pinpoint where it happens, in the actor system, persistence layer or somewhere else:

I have an actor system running that consumes messages from zeroMQ sub socket. The messages relate to a large number of distinct tracking units, each being represented by an in-memory persistent actor. This is typical runtime metrics:

*************************************************************************
* System uptime: 0h 40m 0s : Serving 65559 units -> 1246060 messages
*------------------------------------------------------------------------
* unit_shard1: Serving 12997 units -> Processed 246764 messages
* unit_shard2: Serving 13094 units -> Processed 252199 messages
* unit_shard3: Serving 13247 units -> Processed 251718 messages
* unit_shard4: Serving 13207 units -> Processed 250569 messages
* unit_shard5: Serving 13014 units -> Processed 244810 messages
*------------------------------------------------------------------------
* Overall message processing rate: 519 msg/sec
*------------------------------------------------------------------------
* Processing at 531.0 msg/sec, over current  5 minute interval
*************************************************************************

The above status message is produced by a scheduled request (e.g. 5 minute intervals) and received by an actor who then queries each shard for its throughput.
My question is: Is akka-persitence-cassandra capable of supporting the throughput?

I get Out-of-memory errors or sometimes the log file displays a single line messages:
"killed"
and then the whole actor system stops. No where in my application is a kill message sent to any actor or supervisor.
The shards are currently just concurrent groupings running in a single VM, but will in future be distributed in a cluster along with Cassandra.
I have varied with the number of shards and the Maximum memory allocated to the VM, but it seems to happen around 70 000 actors.
Do you have any comments or observations?

Regards
Ian







zenAptix (Pty) Ltd
176 Dorp Street. Stellenbosch,
South Africa

Work: +27 21 887 3110
Mobile: +27 82 887 0926
web: http://www.zenaptix.com <http://www.zenaptix.com/>

**Comment by krasserm** [comment]
> I would like to consider your offer for professional support and will discuss it with my client. Do you have a rate chart or consulting fee I can use?

Please contact me via email regarding details.

> * Overall message processing rate: 519 msg/sec 
> ...
> My question is: Is akka-persitence-cassandra capable of supporting the throughput? 

Yes, absolutely.

> I get Out-of-memory errors or sometimes the log file displays a single line messages: "killed" ... it seems to happen around 70 000 actors. Do you have any comments or observations? 

Without knowing details about your application, it's hard to say where the problem is located. If you can provide a failing test, please open a ticket [here](https://github.com/krasserm/akka-persistence-cassandra/issues).

Thanks,
Martin

**Comment by krasserm** [comment]
See #11
