### ISSUE TITLE
Request for fs2 Support

### ISSUE THREAD

**Issue by beefyhalo** [krasserm/streamz#16]
scalaz-stream's redesign to fs2 will be ready soon, and it would be fantastic to support it in this library. Particularly for me, the akka-persistence module.

What do you think?

**Comment by volkerstampa** [comment]
@beefyhalo Certainly makes a lot of sense, however fs2 has quite a different API. So looks like we have to rewrite lots of streamz which will take quite some time. Of course pull-requests are welcome to speed things up :-)

**Comment by beefyhalo** [comment]
Cool! Honestly I'd love to contribute. Gonna need some more time studying fs2 before I'm ready though..
In the meantime, check out this tasty resource https://github.com/ktonga/fs2-melancholy

**Comment by krasserm** [comment]
Now in master
