### ISSUE TITLE
Replace deprecated actor publisher with graph stage

### ISSUE THREAD

**Issue by krasserm** [krasserm/streamz#32]

**Comment by fdoumet** [comment]
Any milestone for this?

**Comment by notxcain** [comment]
I think it is totally possible to just use `Source.queue` and `Sink.queue` for `fs2` converters instead of custom `GraphStage`

**Comment by krasserm** [comment]
Please give it a try, would be a very important step!

**Comment by krasserm** [comment]
@notxcain do you want me to wait with the 0.10-M1 release until this ticket is closed?

**Comment by krasserm** [comment]
Closed with #52
