### ISSUE TITLE
FS2 0.10 compatibility

### ISSUE THREAD

**Issue by durban** [krasserm/streamz#38]
Are there plans for a release compatible with FS2 0.10 (0.10.0-M2 at the moment)?

**Comment by krasserm** [comment]
No concrete timeline yet but latest when 0.10 final is out. If there are no major issues with upgrading I'm happy to release a 0.10-compatible milestone earlier. Will work through the migration guide next week and see how far I get. Will keep you updated here ...

**Comment by durban** [comment]
Great, thank you!

**Comment by krasserm** [comment]
Just pushed the [FS2 0.10.0-M2 upgrade](https://github.com/krasserm/streamz/commit/7632f909a7f3f4dcfe143c4acaa73f97880653e9) to [branch fs2-010](https://github.com/krasserm/streamz/tree/fs2-010). I also updated the documentation on this branch. Would be great if you could give it a try and let me know before releasing a streamz milestone. Take a look at the [examples diff](https://github.com/krasserm/streamz/commit/7632f909a7f3f4dcfe143c4acaa73f97880653e9#diff-f256d88ba323d9034c0474b43d722dde) regarding the necessary changes - a migration should be rather straightforward.

**Comment by durban** [comment]
Thanks, I've tested it by locally publishing, and it seems to work fine. Although my usage of Streamz is quite simplistic currently (see [here](https://github.com/durban/seals/blob/wip-issue55/examples/lib/client/src/main/scala/com/example/lib/Client.scala#L68)).

**Comment by krasserm** [comment]
Thanks for testing, will cut a milestone release soon.

**Comment by krasserm** [comment]
I just published 0.9-M1. See also https://gitter.im/krasserm/streamz?at=5961dbac4bcd78af568fd680

**Comment by durban** [comment]
Thanks for the release, it works fine.
