### ISSUE TITLE
How to use jms component in application ack mode?

### ISSUE THREAD

**Issue by konaleksey123** [krasserm/streamz#41]
Hello. Is there a way to use jms component in application ack mode? In akka-camel there is a `def autoAck: Boolean` method. It would be nice for example if I can use `Sink.actorRefWithAck` which send ack message to endpoint too. Thanks.

**Comment by krasserm** [comment]
Only auto-ack is supported at the moment. I just created #40 to cover application-level ACKs. Please use the [streamz forum](https://gitter.im/krasserm/streamz) for questions like that. Closing this ticket as duplicate.
