### ISSUE TITLE
Upgrade to latest dependency versions

### ISSUE THREAD

**Issue by krasserm** [krasserm/streamz#42]

**Comment by goedelsoup** [comment]
Looking for any assistance on this? We hit a hiccup running latest fs2 due to a method name changing.

**Comment by krasserm** [comment]
I found two compile errors with fs2 0.10.0-M10 (regarding `Stream.onError` and `Stream.fail`). There are also problems with the latest version of Apache Camel (2.20.1). Do you see further issues? I'll fix that this week and publish to master. I'll make a new release when fs2 0.10 is final.

**Comment by krasserm** [comment]
@goedelsoup I just pushed the upgrade to fs2 0.10.0-M10 to master.

**Comment by goedelsoup** [comment]
We're running off of master now and seems to have resolved all the issues we were seeing. Will report back if anything else stems up, but lgtm for now.

**Comment by missingfaktor** [comment]
We tried running `streamz-converter 0.9-M1` with `fs2 0.10.1` but got method-not-found errors. The code on `streamz-converter trunk` however works just fine with `fs2 0.10.1`. Could we have a new release, please? :) Happy to help out if we can.

**Comment by krasserm** [comment]
@sure, will release soon

**Comment by krasserm** [comment]
Done with #45

**Comment by krasserm** [comment]
@missingfaktor released 😃

**Comment by missingfaktor** [comment]
Ooooh. Thanks so much, @krasserm!
