### ISSUE TITLE
Builds for Scala 2.13 (-M5) in Central Maven Repo

### ISSUE THREAD

**Issue by unoexperto** [krasserm/streamz#61]
Could you please push builds for Scala 2.13 (-M5) to Central Maven Repo ?

**Comment by unoexperto** [comment]
@krasserm Martin, could you please take a look at it ? I did conversion but for some reason tests

    "propagate cancellation from FS2 sink to AS sink (on FS2 sink completion)"
    "propagate cancellation from FS2 sink to AS sink (on FS2 sink error)"

fail because graph ends prematurely. I couldn't identity why.

**Comment by Daenyth** [comment]
@unoexperto do you have a fork up with the changes?

**Comment by Daenyth** [comment]
I've merged the 2.13 changes - I will try to find some time to do a release soon. I'd also like to get sbt-bintray set up to ease the process going forward

**Comment by Daenyth** [comment]
I just updated the dependencies properly for it. I need to do the manual release on bintray. If I can get time tomorrow I'll do it then, otherwise I'll shoot to get it out next week

**Comment by Daenyth** [comment]
Specifically I'll be putting out an RC1 build, because there's a flapping test in master and I don't know yet if it's a real bug or a broken test

**Comment by larousso** [comment]
Ok thanks a lot !

**Comment by Daenyth** [comment]
Published: https://github.com/krasserm/streamz/releases/tag/0.11-RC1

I just need to get the docs on gh-pages updated
