### ISSUE TITLE
Conversion from `fs2.Stream` to Akka `Source` Requires `ContextShift[IO]`

### ISSUE THREAD

**Issue by robinspollak** [krasserm/streamz#62]
Hello!

The following code does not compile with the implicits and imports specified in the documentation/examples:

```
    AkkaSource .fromGraph(
            stream (: fs2.Stream[IO, Int])
            .toSource
      )
```

with the error:

`value toSource is not a member of fs2.Stream[cats.effect.IO, Int]`

However, this code:

```
  implicit val cs = IO.contextShift(ec)
    AkkaSource .fromGraph(
            stream (: fs2.Stream[IO, Int])
            .toSource
      )
```

compiles as expected. It would be great to add the requirement for a `ContextShift[IO]` to the documentation!

**Comment by krasserm** [comment]
Hi Robin, thanks for reporting. Do you mind creating a pull request?

**Comment by robinspollak** [comment]
Sorry for the delay, just seeing this now. Does !64 work?
